version: '3.7'
services:
  app:
    build:
      context: .
      target: dev
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 4042:3000
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: ./config/postgres
        target: /docker-entrypoint-initdb.d/
    restart: unless-stopped
volumes:
  postgres:
