version: '3.7'
services:
  app:
    build:
      target: prod
    restart: always
    volumes:
      - type: bind
        source: ./public
        target: /usr/src/app/public
  postgres:
    restart: always
  redis:
    restart: always
  nginx:
    restart: always
    ports:
      - 5003:80
    volumes:
      - type: bind
        source: ./config/nginx/nginx.prod.conf
        target: /etc/nginx/nginx.conf
        read_only: true
