version: '3.7'
services:
  app:
    volumes:
      - ./public:/usr/src/app/public
      - ./dist:/usr/src/app/dist
      - ./src:/usr/src/app/src
  postgres:
    ports:
      - 51432:5432
  nginx:
    volumes:
      - type: bind
        source: ./config/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    logging:
      options:
        max-size: '1m'
        max-file: '1'
